---------------------------------------
--Скрипт создания структуры базы данных
---------------------------------------

DROP TABLE IF EXISTS roles CASCADE;
CREATE TABLE roles (
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(50) DEFAULT NULL
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
	id SERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(255) DEFAULT NULL,
	password VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS users_roles;
CREATE TABLE users_roles (
	user_id INT NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
	role_id INT NOT NULL REFERENCES roles ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (user_id, role_id)
);

DROP TABLE IF EXISTS news CASCADE;
CREATE TABLE news (
	id SERIAL NOT NULL PRIMARY KEY,
	author_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	name VARCHAR(255) DEFAULT NULL,
	article TEXT DEFAULT NULL,
	date_of_creation DATE NOT NULL
);