// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestsSKB
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// adminAuthorization - Use 'adminAuthorizationParams' to pass parameters into this method.
        /// </summary>
        public void adminAuthorization()
        {
            #region Variable Declarations
            HtmlHyperlink uIВходHyperlink = this.UIНоваявкладкаInternetWindow.UIСКБDocument.UIНайтиРегистрацияВходPane.UIВходHyperlink;
            HtmlEdit uIUsernameEdit = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UIPasswordEdit;
            HtmlButton uIВойтиButton = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UICommandCustom.UIВойтиButton;
            HtmlHyperlink uIВыходHyperlink = this.UIНоваявкладкаInternetWindow.UIСКБDocument1.UIНайтиЛичныйкабинетВыPane.UIВыходHyperlink;
            #endregion

            // Click 'Вход' link
            Mouse.Click(uIВходHyperlink, new Point(35, 17));

            // Type 'admin' in 'username' text box
            uIUsernameEdit.Text = this.adminAuthorizationParams.UIUsernameEditText;

            // Type '{Tab}' in 'username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.adminAuthorizationParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'password' text box
            uIPasswordEdit.Password = this.adminAuthorizationParams.UIPasswordEditPassword;

            // Click 'Войти' button
            Mouse.Click(uIВойтиButton, new Point(26, 23));

            // Click 'Выход' link
            Mouse.Click(uIВыходHyperlink, new Point(70, 26));
        }
        
        /// <summary>
        /// customerAuthorization - Use 'customerAuthorizationParams' to pass parameters into this method.
        /// </summary>
        public void customerAuthorization()
        {
            #region Variable Declarations
            HtmlHyperlink uIВходHyperlink = this.UIНоваявкладкаInternetWindow.UIСКБDocument.UIНайтиРегистрацияВходPane.UIВходHyperlink;
            HtmlEdit uIUsernameEdit = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UIPasswordEdit;
            HtmlButton uIВойтиButton = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UICommandCustom.UIВойтиButton;
            HtmlHyperlink uIВыходHyperlink = this.UIНоваявкладкаInternetWindow.UIСКБDocument1.UIНайтиЛичныйкабинетВыPane.UIВыходHyperlink;
            #endregion

            // Click 'Вход' link
            Mouse.Click(uIВходHyperlink, new Point(47, 21));

            // Type 'customer' in 'username' text box
            uIUsernameEdit.Text = this.customerAuthorizationParams.UIUsernameEditText;

            // Type '{Tab}' in 'username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.customerAuthorizationParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'password' text box
            uIPasswordEdit.Password = this.customerAuthorizationParams.UIPasswordEditPassword;

            // Click 'Войти' button
            Mouse.Click(uIВойтиButton, new Point(31, 25));

            // Click 'Выход' link
            Mouse.Click(uIВыходHyperlink, new Point(66, 7));
        }
        
        /// <summary>
        /// UserAuthorization - Use 'UserAuthorizationParams' to pass parameters into this method.
        /// </summary>
        public void UserAuthorization()
        {
            #region Variable Declarations
            HtmlHyperlink uIВходHyperlink = this.UIНоваявкладкаInternetWindow.UIСКБDocument.UIНайтиРегистрацияВходPane.UIВходHyperlink;
            HtmlEdit uIUsernameEdit = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UIPasswordEdit;
            HtmlButton uIВойтиButton = this.UIНоваявкладкаInternetWindow.UIАвторизацияDocument.UICommandCustom.UIВойтиButton;
            HtmlDocument uIСКБDocument1 = this.UIНоваявкладкаInternetWindow.UIСКБDocument1;
            HtmlHyperlink uIВыходHyperlink = this.UIНоваявкладкаInternetWindow.UIСКБDocument1.UIНайтиЛичныйкабинетВыPane.UIВыходHyperlink;
            #endregion

            // Go to web page 'http://localhost:8080/' using new browser instance
            this.UIНоваявкладкаInternetWindow.LaunchUrl(new System.Uri(this.UserAuthorizationParams.UIНоваявкладкаInternetWindowUrl));

            // Click 'Вход' link
            Mouse.Click(uIВходHyperlink, new Point(57, 43));

            // Type 'user' in 'username' text box
            uIUsernameEdit.Text = this.UserAuthorizationParams.UIUsernameEditText;

            // Type '********' in 'password' text box
            uIPasswordEdit.Password = this.UserAuthorizationParams.UIPasswordEditPassword;

            // Click 'Войти' button
            Mouse.Click(uIВойтиButton, new Point(33, 18));

            // Move 'СКБ' document
            Mouse.StartDragging(uIСКБDocument1, new Point(115, 210));
            Mouse.StopDragging(uIСКБDocument1, -113, -5);

            // Right-Click 'СКБ' document
            Mouse.Click(uIСКБDocument1, MouseButtons.Right, ModifierKeys.None, new Point(8, 206));

            // Click 'СКБ' document
            Mouse.Click(uIСКБDocument1, new Point(25, 206));

            // Click 'Выход' link
            Mouse.Click(uIВыходHyperlink, new Point(77, 21));
        }
        
        #region Properties
        public virtual adminAuthorizationParams adminAuthorizationParams
        {
            get
            {
                if ((this.madminAuthorizationParams == null))
                {
                    this.madminAuthorizationParams = new adminAuthorizationParams();
                }
                return this.madminAuthorizationParams;
            }
        }
        
        public virtual customerAuthorizationParams customerAuthorizationParams
        {
            get
            {
                if ((this.mcustomerAuthorizationParams == null))
                {
                    this.mcustomerAuthorizationParams = new customerAuthorizationParams();
                }
                return this.mcustomerAuthorizationParams;
            }
        }
        
        public virtual UserAuthorizationParams UserAuthorizationParams
        {
            get
            {
                if ((this.mUserAuthorizationParams == null))
                {
                    this.mUserAuthorizationParams = new UserAuthorizationParams();
                }
                return this.mUserAuthorizationParams;
            }
        }
        
        public UIНоваявкладкаInternetWindow UIНоваявкладкаInternetWindow
        {
            get
            {
                if ((this.mUIНоваявкладкаInternetWindow == null))
                {
                    this.mUIНоваявкладкаInternetWindow = new UIНоваявкладкаInternetWindow();
                }
                return this.mUIНоваявкладкаInternetWindow;
            }
        }
        
        public UIСообщениесвебстраницWindow UIСообщениесвебстраницWindow
        {
            get
            {
                if ((this.mUIСообщениесвебстраницWindow == null))
                {
                    this.mUIСообщениесвебстраницWindow = new UIСообщениесвебстраницWindow();
                }
                return this.mUIСообщениесвебстраницWindow;
            }
        }
        #endregion
        
        #region Fields
        private adminAuthorizationParams madminAuthorizationParams;
        
        private customerAuthorizationParams mcustomerAuthorizationParams;
        
        private UserAuthorizationParams mUserAuthorizationParams;
        
        private UIНоваявкладкаInternetWindow mUIНоваявкладкаInternetWindow;
        
        private UIСообщениесвебстраницWindow mUIСообщениесвебстраницWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'adminAuthorization'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class adminAuthorizationParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'username' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'password' text box
        /// </summary>
        public string UIPasswordEditPassword = "ltMtR4VOfdZS3D8xaljxesqUwEXKaQEX";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'customerAuthorization'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class customerAuthorizationParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'customer' in 'username' text box
        /// </summary>
        public string UIUsernameEditText = "customer";
        
        /// <summary>
        /// Type '{Tab}' in 'username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'password' text box
        /// </summary>
        public string UIPasswordEditPassword = "EXeGolg/ZzKdz70tAf+cmD5CTdoPja9I";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'UserAuthorization'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UserAuthorizationParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:8080/' using new browser instance
        /// </summary>
        public string UIНоваявкладкаInternetWindowUrl = "http://localhost:8080/";
        
        /// <summary>
        /// Type 'user' in 'username' text box
        /// </summary>
        public string UIUsernameEditText = "user";
        
        /// <summary>
        /// Type '********' in 'password' text box
        /// </summary>
        public string UIPasswordEditPassword = "VLLA+bJzNf882FWpmiwJPY0v6P7+sGGK";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIНоваявкладкаInternetWindow : BrowserWindow
    {
        
        public UIНоваявкладкаInternetWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Новая вкладка";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Новая вкладка");
            this.WindowTitles.Add("http://localhost:8080/");
            this.WindowTitles.Add("СКБ");
            this.WindowTitles.Add("Регистрация");
            this.WindowTitles.Add("Авторизация");
            this.WindowTitles.Add("О нас");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIСКБDocument UIСКБDocument
        {
            get
            {
                if ((this.mUIСКБDocument == null))
                {
                    this.mUIСКБDocument = new UIСКБDocument(this);
                }
                return this.mUIСКБDocument;
            }
        }
        
        public UIАвторизацияDocument UIАвторизацияDocument
        {
            get
            {
                if ((this.mUIАвторизацияDocument == null))
                {
                    this.mUIАвторизацияDocument = new UIАвторизацияDocument(this);
                }
                return this.mUIАвторизацияDocument;
            }
        }
        
        public UIСКБDocument1 UIСКБDocument1
        {
            get
            {
                if ((this.mUIСКБDocument1 == null))
                {
                    this.mUIСКБDocument1 = new UIСКБDocument1(this);
                }
                return this.mUIСКБDocument1;
            }
        }
        
        public UIНоваявкладкаDocument UIНоваявкладкаDocument
        {
            get
            {
                if ((this.mUIНоваявкладкаDocument == null))
                {
                    this.mUIНоваявкладкаDocument = new UIНоваявкладкаDocument(this);
                }
                return this.mUIНоваявкладкаDocument;
            }
        }
        
        public UIСКБDocument2 UIСКБDocument2
        {
            get
            {
                if ((this.mUIСКБDocument2 == null))
                {
                    this.mUIСКБDocument2 = new UIСКБDocument2(this);
                }
                return this.mUIСКБDocument2;
            }
        }
        
        public UIОнасDocument UIОнасDocument
        {
            get
            {
                if ((this.mUIОнасDocument == null))
                {
                    this.mUIОнасDocument = new UIОнасDocument(this);
                }
                return this.mUIОнасDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIСКБDocument mUIСКБDocument;
        
        private UIАвторизацияDocument mUIАвторизацияDocument;
        
        private UIСКБDocument1 mUIСКБDocument1;
        
        private UIНоваявкладкаDocument mUIНоваявкладкаDocument;
        
        private UIСКБDocument2 mUIСКБDocument2;
        
        private UIОнасDocument mUIОнасDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIСКБDocument : HtmlDocument
    {
        
        public UIСКБDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "СКБ";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/index";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:8080/index?logout";
            this.WindowTitles.Add("СКБ");
            #endregion
        }
        
        #region Properties
        public UIНайтиРегистрацияВходPane UIНайтиРегистрацияВходPane
        {
            get
            {
                if ((this.mUIНайтиРегистрацияВходPane == null))
                {
                    this.mUIНайтиРегистрацияВходPane = new UIНайтиРегистрацияВходPane(this);
                }
                return this.mUIНайтиРегистрацияВходPane;
            }
        }
        #endregion
        
        #region Fields
        private UIНайтиРегистрацияВходPane mUIНайтиРегистрацияВходPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIНайтиРегистрацияВходPane : HtmlDiv
    {
        
        public UIНайтиРегистрацияВходPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "navbar";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Найти \r\n Регистрация \r\n\r\n\r\n Вход ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "hidden-lg navbar-collapse collapse navbar-right main-navbar";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"hidden-lg navbar-collapse collapse navbar-right main-navbar\" id=\"navbar\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("СКБ");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIВходHyperlink
        {
            get
            {
                if ((this.mUIВходHyperlink == null))
                {
                    this.mUIВходHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Вход ";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/authorization";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:8080/authorization";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "nav-link";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"nav-link\" href=\"/authorization\"";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIВходHyperlink.WindowTitles.Add("СКБ");
                    #endregion
                }
                return this.mUIВходHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIВходHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIАвторизацияDocument : HtmlDocument
    {
        
        public UIАвторизацияDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Авторизация";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/authorization";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:8080/authorization";
            this.WindowTitles.Add("Авторизация");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "username";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"username\" class=\"form-control\" aut";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUsernameEdit.WindowTitles.Add("Авторизация");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"password\" class=\"form-control\" typ";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Авторизация");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public UICommandCustom UICommandCustom
        {
            get
            {
                if ((this.mUICommandCustom == null))
                {
                    this.mUICommandCustom = new UICommandCustom(this);
                }
                return this.mUICommandCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private UICommandCustom mUICommandCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICommandCustom : HtmlCustom
    {
        
        public UICommandCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "command";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "form-horizontal";
            this.FilterProperties["ControlDefinition"] = "class=\"form-horizontal\" id=\"command\" act";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Авторизация");
            #endregion
        }
        
        #region Properties
        public HtmlButton UIВойтиButton
        {
            get
            {
                if ((this.mUIВойтиButton == null))
                {
                    this.mUIВойтиButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIВойтиButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIВойтиButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIВойтиButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Войти";
                    this.mUIВойтиButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIВойтиButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIВойтиButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary btn-lg text-right";
                    this.mUIВойтиButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary btn-lg text-right";
                    this.mUIВойтиButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIВойтиButton.WindowTitles.Add("Авторизация");
                    #endregion
                }
                return this.mUIВойтиButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUIВойтиButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIСКБDocument1 : HtmlDocument
    {
        
        public UIСКБDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "СКБ";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:8080/?login";
            this.WindowTitles.Add("СКБ");
            #endregion
        }
        
        #region Properties
        public UIНайтиЛичныйкабинетВыPane UIНайтиЛичныйкабинетВыPane
        {
            get
            {
                if ((this.mUIНайтиЛичныйкабинетВыPane == null))
                {
                    this.mUIНайтиЛичныйкабинетВыPane = new UIНайтиЛичныйкабинетВыPane(this);
                }
                return this.mUIНайтиЛичныйкабинетВыPane;
            }
        }
        
        public UIMain_navCustom UIMain_navCustom
        {
            get
            {
                if ((this.mUIMain_navCustom == null))
                {
                    this.mUIMain_navCustom = new UIMain_navCustom(this);
                }
                return this.mUIMain_navCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIНайтиЛичныйкабинетВыPane mUIНайтиЛичныйкабинетВыPane;
        
        private UIMain_navCustom mUIMain_navCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIНайтиЛичныйкабинетВыPane : HtmlDiv
    {
        
        public UIНайтиЛичныйкабинетВыPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "navbar";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Найти \r\n Личный кабинет \r\n\r\n\r\n Выход ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "hidden-lg navbar-collapse collapse navbar-right main-navbar";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"hidden-lg navbar-collapse collapse navbar-right main-navbar\" id=\"navbar\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("СКБ");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIВыходHyperlink
        {
            get
            {
                if ((this.mUIВыходHyperlink == null))
                {
                    this.mUIВыходHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIВыходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIВыходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIВыходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIВыходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Выход ";
                    this.mUIВыходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIВыходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIВыходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:8080/?login#";
                    this.mUIВыходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "nav-link";
                    this.mUIВыходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"nav-link\" onclick=\"document.forms";
                    this.mUIВыходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIВыходHyperlink.WindowTitles.Add("СКБ");
                    #endregion
                }
                return this.mUIВыходHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIВыходHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMain_navCustom : HtmlCustom
    {
        
        public UIMain_navCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "main_nav";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "nav nav-justified";
            this.FilterProperties["ControlDefinition"] = "class=\"nav nav-justified\" id=\"main_nav\"";
            this.FilterProperties["TagInstance"] = "2";
            this.WindowTitles.Add("СКБ");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIОнасHyperlink
        {
            get
            {
                if ((this.mUIОнасHyperlink == null))
                {
                    this.mUIОнасHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIОнасHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIОнасHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIОнасHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIОнасHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "О нас";
                    this.mUIОнасHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/about";
                    this.mUIОнасHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIОнасHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:8080/about";
                    this.mUIОнасHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIОнасHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/about\"";
                    this.mUIОнасHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUIОнасHyperlink.WindowTitles.Add("СКБ");
                    #endregion
                }
                return this.mUIОнасHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIОнасHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIНоваявкладкаDocument : HtmlDocument
    {
        
        public UIНоваявкладкаDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Новая вкладка";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/spartan/ientp";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.msn.com/spartan/ientp?locale=ru-RU&market=RU&enableregulatorypsm=0&NT" +
                "Logo=1&IsFRE=0";
            this.WindowTitles.Add("Новая вкладка");
            #endregion
        }
        
        #region Properties
        public UIJstopsitesCustom UIJstopsitesCustom
        {
            get
            {
                if ((this.mUIJstopsitesCustom == null))
                {
                    this.mUIJstopsitesCustom = new UIJstopsitesCustom(this);
                }
                return this.mUIJstopsitesCustom;
            }
        }
        
        public HtmlCustom UIHeadercommonCustom
        {
            get
            {
                if ((this.mUIHeadercommonCustom == null))
                {
                    this.mUIHeadercommonCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIHeadercommonCustom.SearchProperties["TagName"] = "HEADER";
                    this.mUIHeadercommonCustom.SearchProperties["Id"] = "header-common";
                    this.mUIHeadercommonCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIHeadercommonCustom.FilterProperties["Class"] = "no-overlay stick-enabled";
                    this.mUIHeadercommonCustom.FilterProperties["ControlDefinition"] = "class=\"no-overlay stick-enabled\" id=\"hea";
                    this.mUIHeadercommonCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIHeadercommonCustom.WindowTitles.Add("Новая вкладка");
                    #endregion
                }
                return this.mUIHeadercommonCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIJstopsitesCustom mUIJstopsitesCustom;
        
        private HtmlCustom mUIHeadercommonCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIJstopsitesCustom : HtmlCustom
    {
        
        public UIJstopsitesCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "js-topsites";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "has-curated";
            this.FilterProperties["ControlDefinition"] = "class=\"has-curated\" id=\"js-topsites\" dat";
            this.FilterProperties["TagInstance"] = "5";
            this.WindowTitles.Add("Новая вкладка");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIМагазинMicrosoftHyperlink
        {
            get
            {
                if ((this.mUIМагазинMicrosoftHyperlink == null))
                {
                    this.mUIМагазинMicrosoftHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIМагазинMicrosoftHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIМагазинMicrosoftHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIМагазинMicrosoftHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIМагазинMicrosoftHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "  \r\nМагазин Microsoft";
                    this.mUIМагазинMicrosoftHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/click";
                    this.mUIМагазинMicrosoftHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Магазин Microsoft\n‪http://clk.tradedoubler.com/click?p=270367&a=2811333&epi=Edge_" +
                        "RURU_TopSites&url=https://microsoftstore.ru/‬";
                    this.mUIМагазинMicrosoftHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://clk.tradedoubler.com/click?p=270367&a=2811333&epi=Edge_RURU_TopSites&url=h" +
                        "ttps://microsoftstore.ru/";
                    this.mUIМагазинMicrosoftHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIМагазинMicrosoftHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Магазин Microsoft&#10;‪http://clk";
                    this.mUIМагазинMicrosoftHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIМагазинMicrosoftHyperlink.WindowTitles.Add("Новая вкладка");
                    #endregion
                }
                return this.mUIМагазинMicrosoftHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIМагазинMicrosoftHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIСКБDocument2 : HtmlDocument
    {
        
        public UIСКБDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "СКБ";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:8080/";
            this.WindowTitles.Add("СКБ");
            #endregion
        }
        
        #region Properties
        public UIНайтиРегистрацияВходPane1 UIНайтиРегистрацияВходPane
        {
            get
            {
                if ((this.mUIНайтиРегистрацияВходPane == null))
                {
                    this.mUIНайтиРегистрацияВходPane = new UIНайтиРегистрацияВходPane1(this);
                }
                return this.mUIНайтиРегистрацияВходPane;
            }
        }
        #endregion
        
        #region Fields
        private UIНайтиРегистрацияВходPane1 mUIНайтиРегистрацияВходPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIНайтиРегистрацияВходPane1 : HtmlDiv
    {
        
        public UIНайтиРегистрацияВходPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "navbar";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Найти \r\n Регистрация \r\n\r\n\r\n Вход ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "hidden-lg navbar-collapse collapse navbar-right main-navbar";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"hidden-lg navbar-collapse collapse navbar-right main-navbar\" id=\"navbar\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("СКБ");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIВходHyperlink
        {
            get
            {
                if ((this.mUIВходHyperlink == null))
                {
                    this.mUIВходHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIВходHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Вход ";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/authorization";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:8080/authorization";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "nav-link";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"nav-link\" href=\"/authorization\"";
                    this.mUIВходHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIВходHyperlink.WindowTitles.Add("СКБ");
                    #endregion
                }
                return this.mUIВходHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIВходHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIОнасDocument : HtmlDocument
    {
        
        public UIОнасDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "О нас";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/about";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:8080/about";
            this.WindowTitles.Add("О нас");
            #endregion
        }
        
        #region Properties
        public HtmlButton UIРедактироватьButton
        {
            get
            {
                if ((this.mUIРедактироватьButton == null))
                {
                    this.mUIРедактироватьButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIРедактироватьButton.SearchProperties[HtmlButton.PropertyNames.Id] = "about-toggle-button";
                    this.mUIРедактироватьButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIРедактироватьButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " Редактировать ";
                    this.mUIРедактироватьButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIРедактироватьButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIРедактироватьButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-back btn-lg";
                    this.mUIРедактироватьButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-back btn-lg\" id=\"about-to";
                    this.mUIРедактироватьButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIРедактироватьButton.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIРедактироватьButton;
            }
        }
        
        public UIAboutPageCustom UIAboutPageCustom
        {
            get
            {
                if ((this.mUIAboutPageCustom == null))
                {
                    this.mUIAboutPageCustom = new UIAboutPageCustom(this);
                }
                return this.mUIAboutPageCustom;
            }
        }
        
        public HtmlDiv UIУнасвсёхорошомыСКБPane
        {
            get
            {
                if ((this.mUIУнасвсёхорошомыСКБPane == null))
                {
                    this.mUIУнасвсёхорошомыСКБPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIУнасвсёхорошомыСКБPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIУнасвсёхорошомыСКБPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIУнасвсёхорошомыСКБPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "У нас всё хорошо, мы СКБ.";
                    this.mUIУнасвсёхорошомыСКБPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIУнасвсёхорошомыСКБPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-xs-12";
                    this.mUIУнасвсёхорошомыСКБPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-xs-12\"";
                    this.mUIУнасвсёхорошомыСКБPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "150";
                    this.mUIУнасвсёхорошомыСКБPane.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIУнасвсёхорошомыСКБPane;
            }
        }
        
        public UIAboutPageCustom1 UIAboutPageCustom1
        {
            get
            {
                if ((this.mUIAboutPageCustom1 == null))
                {
                    this.mUIAboutPageCustom1 = new UIAboutPageCustom1(this);
                }
                return this.mUIAboutPageCustom1;
            }
        }
        
        public UIAboutPageCustom2 UIAboutPageCustom2
        {
            get
            {
                if ((this.mUIAboutPageCustom2 == null))
                {
                    this.mUIAboutPageCustom2 = new UIAboutPageCustom2(this);
                }
                return this.mUIAboutPageCustom2;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUIРедактироватьButton;
        
        private UIAboutPageCustom mUIAboutPageCustom;
        
        private HtmlDiv mUIУнасвсёхорошомыСКБPane;
        
        private UIAboutPageCustom1 mUIAboutPageCustom1;
        
        private UIAboutPageCustom2 mUIAboutPageCustom2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAboutPageCustom : HtmlCustom
    {
        
        public UIAboutPageCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "aboutPage";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"aboutPage\" action=\"/about?_csrf=66e7";
            this.FilterProperties["TagInstance"] = "3";
            this.WindowTitles.Add("О нас");
            #endregion
        }
        
        #region Properties
        public HtmlEditableDiv UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new HtmlEditableDiv(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.InnerText] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "note-editable panel-body";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"note-editable panel-body\" contenteditable=\"true\"";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "84";
                    this.mUIItemEdit.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public HtmlButton UIСохранитьизмененияButton
        {
            get
            {
                if ((this.mUIСохранитьизмененияButton == null))
                {
                    this.mUIСохранитьизмененияButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIСохранитьизмененияButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIСохранитьизмененияButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIСохранитьизмененияButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Сохранить изменения";
                    this.mUIСохранитьизмененияButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIСохранитьизмененияButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIСохранитьизмененияButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUIСохранитьизмененияButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\"";
                    this.mUIСохранитьизмененияButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "161";
                    this.mUIСохранитьизмененияButton.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIСохранитьизмененияButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEditableDiv mUIItemEdit;
        
        private HtmlButton mUIСохранитьизмененияButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAboutPageCustom1 : HtmlCustom
    {
        
        public UIAboutPageCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "aboutPage";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"aboutPage\" action=\"/about?_csrf=8012";
            this.FilterProperties["TagInstance"] = "3";
            this.WindowTitles.Add("О нас");
            #endregion
        }
        
        #region Properties
        public HtmlEditableDiv UIУнасвсёхорошомыСКБEdit
        {
            get
            {
                if ((this.mUIУнасвсёхорошомыСКБEdit == null))
                {
                    this.mUIУнасвсёхорошомыСКБEdit = new HtmlEditableDiv(this);
                    #region Search Criteria
                    this.mUIУнасвсёхорошомыСКБEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIУнасвсёхорошомыСКБEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIУнасвсёхорошомыСКБEdit.FilterProperties[HtmlEdit.PropertyNames.InnerText] = "У нас всё хорошо, мы СКБ.";
                    this.mUIУнасвсёхорошомыСКБEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIУнасвсёхорошомыСКБEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "note-editable panel-body";
                    this.mUIУнасвсёхорошомыСКБEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"note-editable panel-body\" contenteditable=\"true\"";
                    this.mUIУнасвсёхорошомыСКБEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "84";
                    this.mUIУнасвсёхорошомыСКБEdit.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIУнасвсёхорошомыСКБEdit;
            }
        }
        
        public HtmlEditableDiv UIУнасвсёхорошоEdit
        {
            get
            {
                if ((this.mUIУнасвсёхорошоEdit == null))
                {
                    this.mUIУнасвсёхорошоEdit = new HtmlEditableDiv(this);
                    #region Search Criteria
                    this.mUIУнасвсёхорошоEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIУнасвсёхорошоEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.InnerText] = "У нас всё хорошо.";
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "note-editable panel-body";
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"note-editable panel-body\" contenteditable=\"true\"";
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "84";
                    this.mUIУнасвсёхорошоEdit.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIУнасвсёхорошоEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEditableDiv mUIУнасвсёхорошомыСКБEdit;
        
        private HtmlEditableDiv mUIУнасвсёхорошоEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAboutPageCustom2 : HtmlCustom
    {
        
        public UIAboutPageCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "aboutPage";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"aboutPage\" action=\"/about?_csrf=66f8";
            this.FilterProperties["TagInstance"] = "3";
            this.WindowTitles.Add("О нас");
            #endregion
        }
        
        #region Properties
        public HtmlEditableDiv UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new HtmlEditableDiv(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.InnerText] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "note-editable panel-body";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"note-editable panel-body\" contenteditable=\"true\"";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "84";
                    this.mUIItemEdit.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public HtmlEditableDiv UIУнасвсёхорошоEdit
        {
            get
            {
                if ((this.mUIУнасвсёхорошоEdit == null))
                {
                    this.mUIУнасвсёхорошоEdit = new HtmlEditableDiv(this);
                    #region Search Criteria
                    this.mUIУнасвсёхорошоEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIУнасвсёхорошоEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.InnerText] = "У нас всё хорошо.";
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "note-editable panel-body";
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"note-editable panel-body\" contenteditable=\"true\"";
                    this.mUIУнасвсёхорошоEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "84";
                    this.mUIУнасвсёхорошоEdit.WindowTitles.Add("О нас");
                    #endregion
                }
                return this.mUIУнасвсёхорошоEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEditableDiv mUIItemEdit;
        
        private HtmlEditableDiv mUIУнасвсёхорошоEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIСообщениесвебстраницWindow : WinWindow
    {
        
        public UIСообщениесвебстраницWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Сообщение с веб-страницы";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Сообщение с веб-страницы");
            #endregion
        }
        
        #region Properties
        public UIОКWindow UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow(this);
                }
                return this.mUIОКWindow;
            }
        }
        
        public UIОтменаWindow UIОтменаWindow
        {
            get
            {
                if ((this.mUIОтменаWindow == null))
                {
                    this.mUIОтменаWindow = new UIОтменаWindow(this);
                }
                return this.mUIОтменаWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIОКWindow mUIОКWindow;
        
        private UIОтменаWindow mUIОтменаWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIОКWindow : WinWindow
    {
        
        public UIОКWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Сообщение с веб-страницы");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("Сообщение с веб-страницы");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIОтменаWindow : WinWindow
    {
        
        public UIОтменаWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Сообщение с веб-страницы");
            #endregion
        }
        
        #region Properties
        public WinButton UIОтменаButton
        {
            get
            {
                if ((this.mUIОтменаButton == null))
                {
                    this.mUIОтменаButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОтменаButton.SearchProperties[WinButton.PropertyNames.Name] = "Отмена";
                    this.mUIОтменаButton.WindowTitles.Add("Сообщение с веб-страницы");
                    #endregion
                }
                return this.mUIОтменаButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОтменаButton;
        #endregion
    }
}
